"use client";
import { useState } from "react";
import { FileDown, Loader2, BookOpen, Check } from "lucide-react";
import type { PracticeData } from "@/app/dashboard/usePracticeData";

// ─── Practice Playbook Export ────────────────────────────────────────────────
// Generates a comprehensive text export summarizing firm configuration,
// compliance posture, team structure, and operational metrics.

function buildPlaybook(data: PracticeData, firmName?: string): string {
  const now = new Date().toLocaleString();
  const divider = "═".repeat(64);
  const section = (title: string) => `\n${"─".repeat(3)} ${title} ${"─".repeat(Math.max(0, 56 - title.length))}`;

  const lines: string[] = [
    divider,
    `  ${firmName || "Practice"} — Operational Playbook`,
    `  Generated: ${now}`,
    `  Prepared by Min · Powered by Impacting Advisors`,
    divider,

    section("PRACTICE OVERVIEW"),
    `Total Households:       ${data.totalHouseholds}`,
    `Active Advisors:        ${data.advisors.filter(a => a.name !== "Unassigned" && a.households > 0).length}`,
    `Total Tasks:            ${data.totalTasks}`,
    `Open Tasks:             ${data.openTasks}`,
    `Completed Tasks:        ${data.completedTasks}`,
    `Compliance Reviews:     ${data.complianceReviews}`,
    `Meeting Notes Logged:   ${data.meetingNotes}`,
    `Unsigned Envelopes:     ${data.unsigned}`,

    section("HEALTH SCORE"),
    `Overall Score:          ${data.healthScore}/100`,
    ...data.healthBreakdown.map(b => `  ${b.label.padEnd(26)} ${b.score}% (weight: ${b.weight}%)`),

    section("REVENUE INTELLIGENCE"),
    `Estimated AUM:          $${(data.revenue.estimatedAum / 1e6).toFixed(1)}M${data.fscAvailable ? " (FSC verified)" : " (estimated)"}`,
    `Annual Fee Income:      $${(data.revenue.annualFeeIncome / 1e3).toFixed(0)}K`,
    `Monthly Fee Income:     $${(data.revenue.monthlyFeeIncome / 1e3).toFixed(0)}K`,
    `Fee Schedule:           ${data.assumptions.feeScheduleBps} bps`,
    "",
    "Revenue by Advisor:",
    ...data.revenue.revenuePerAdvisor.map(a => `  ${a.name.padEnd(22)} ${a.households} HH · $${(a.estimatedAum / 1e6).toFixed(1)}M AUM · $${(a.annualFee / 1e3).toFixed(0)}K/yr`),

    section("ADVISOR SCOREBOARD"),
    "Name                   HH   Open  Overdue  Unsigned  Compliance  Meetings90  Score",
    "-".repeat(90),
    ...data.advisors.filter(a => a.name !== "Unassigned").map(a =>
      `${a.name.padEnd(23)} ${String(a.households).padStart(3)}  ${String(a.openTasks).padStart(5)}  ${String(a.overdueTasks).padStart(7)}  ${String(a.unsigned).padStart(8)}  ${String(a.compliancePct + "%").padStart(10)}  ${String(a.meetingsLast90).padStart(10)}  ${String(a.score).padStart(5)}`
    ),

    section("PIPELINE"),
    ...data.pipeline.map(p => `  ${p.label.padEnd(20)} ${p.count} HH · avg ${p.avgDays}d · ${p.stuck} stuck · conv: ${p.conversionRate}%`),

    section("TOP RISKS"),
    ...data.risks.slice(0, 15).map((r, i) => `  ${i + 1}. [${r.severity.toUpperCase()}] ${r.label} — ${r.household} (${r.daysStale}d)`),

    section("WEEKLY COMPARISON"),
    ...data.weeklyComparison.map(w => `  ${w.label.padEnd(22)} This week: ${w.thisWeek}  |  Last week: ${w.lastWeek}  |  Δ ${w.thisWeek - w.lastWeek >= 0 ? "+" : ""}${w.thisWeek - w.lastWeek}`),

    section("OPS STAFF WORKLOAD"),
    ...data.opsStaff.map(s => `  ${s.name.padEnd(20)} Open: ${s.openTasks} · Overdue: ${s.overdueTasks} · Completed/wk: ${s.completedThisWeek} · Score: ${s.score}`),

    "",
    section("COMPLIANCE CONFIGURATION"),
    (() => {
      try {
        const checks = JSON.parse(localStorage.getItem("min-custom-compliance-checks") || "[]");
        if (checks.length === 0) return "  No custom compliance checks defined.";
        return "Custom Checks:\n" + checks.map((c: { label: string; keyword: string; regulation: string; failStatus: string }) =>
          `  • ${c.label} — keyword: "${c.keyword}" · ${c.regulation} · ${c.failStatus === "fail" ? "FAIL" : "WARN"} if missing`
        ).join("\n");
      } catch { return "  Unable to read custom checks."; }
    })(),

    (() => {
      try {
        const schedules = JSON.parse(localStorage.getItem("min-compliance-schedules") || "[]");
        if (schedules.length === 0) return "\n  No scheduled scans configured.";
        return "\nScheduled Scans:\n" + schedules.map((s: { name: string; frequency: string; enabled: boolean; criteria: string }) =>
          `  • ${s.name} — ${s.frequency} · ${s.enabled ? "enabled" : "disabled"} · ${s.criteria === "all" ? "all households" : "threshold-based"}`
        ).join("\n");
      } catch { return "\n  Unable to read schedules."; }
    })(),

    "",
    divider,
    "End of Playbook · " + now,
    "Generated by Min — Powered by Impacting Advisors",
  ];

  return lines.join("\n");
}

// ─── Component ──────────────────────────────────────────────────────────────

export function PracticePlaybook({ data, firmName }: { data: PracticeData; firmName?: string }) {
  const [exporting, setExporting] = useState(false);
  const [done, setDone] = useState(false);

  const handleExport = () => {
    setExporting(true);
    setTimeout(() => {
      const text = buildPlaybook(data, firmName);
      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `practice-playbook-${new Date().toISOString().slice(0, 10)}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setExporting(false);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    }, 500);
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-5">
      <div className="flex items-center gap-4">
        <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center flex-shrink-0">
          <BookOpen size={18} className="text-slate-500" />
        </div>
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-semibold text-slate-700">Practice Playbook</h3>
          <p className="text-xs text-slate-400 mt-0.5">Export a comprehensive snapshot of your practice configuration, team metrics, compliance posture, and operational data.</p>
        </div>
        <button onClick={handleExport} disabled={exporting}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-colors flex-shrink-0 ${done ? "bg-green-100 text-green-700" : "bg-slate-900 text-white hover:bg-slate-800 disabled:opacity-50"}`}>
          {exporting ? <Loader2 size={14} className="animate-spin" /> : done ? <Check size={14} /> : <FileDown size={14} />}
          {exporting ? "Exporting..." : done ? "Downloaded" : "Export Playbook"}
        </button>
      </div>
    </div>
  );
}
