// ─── Onboarding Domain Handlers ──────────────────────────────────────────────
//
// All account-opening workflow steps: funding, MoneyLink, beneficiaries,
// completeness, paperwork, DocuSign config, and DocuSign send.

import { NextResponse } from "next/server";
import { query, update, createTask, createTasksBatch, sanitizeSOQL } from "@/lib/sf-client";
import type { SFContext, TaskInput } from "@/lib/sf-client";
import { validate } from "@/lib/sf-validation";
import { custodian } from "@/lib/custodian";
import { fireWorkflowTrigger } from "@/lib/workflows";

type Handler = (data: unknown, ctx: SFContext) => Promise<NextResponse>;

export const onboardingHandlers: Record<string, Handler> = {
  recordFunding: async (raw, ctx) => {
    const data = validate.recordFunding(raw);
    const note = `FUNDING DETAILS (recorded by Min at ${new Date().toISOString()}):\n` +
      data.fundingDetails.map(f => `• ${f.account}: ${f.detail}`).join("\n") +
      `\n\nPTE Required: ${data.pteRequired ? "YES — auto-generated" : "No"}`;

    const existing = await query(ctx,
      `SELECT Description FROM Account WHERE Id = '${sanitizeSOQL(data.householdId)}' LIMIT 1`
    );
    const prevDesc = (existing[0]?.Description as string) || "";
    const fullDesc = prevDesc ? `${prevDesc}\n\n───────────────────\n\n${note}` : note;
    await update(ctx, "Account", data.householdId, { Description: fullDesc });

    const task = await createTask(ctx, {
      subject: `Funding configured — ${data.familyName} (${data.fundingDetails.length} accounts)`,
      householdId: data.householdId,
      description: note,
    });
    return NextResponse.json({ success: true, task, householdUrl: `${ctx.instanceUrl}/${data.householdId}` });
  },

  recordMoneyLink: async (raw, ctx) => {
    const data = validate.recordMoneyLink(raw);
    const task = await createTask(ctx, {
      subject: `MoneyLink setup — ${data.bankName} (****${data.lastFour})`,
      householdId: data.householdId,
      description: `Bank: ${data.bankName}\nRouting: ****${data.routingLastFour}\nAccount: ****${data.lastFour}\nRecorded by Min at ${new Date().toISOString()}`,
    });
    return NextResponse.json({ success: true, task });
  },

  recordBeneficiaries: async (raw, ctx) => {
    const data = validate.recordBeneficiaries(raw);
    const task = await createTask(ctx, {
      subject: `Beneficiary designations prefilled — ${data.familyName}`,
      householdId: data.householdId,
      description: data.designations.map(d => `• ${d.account}: ${d.beneficiary}`).join("\n") +
        `\n\nPrefilled by Min using ownership rules. Advisor reviewed at ${new Date().toISOString()}`,
    });
    return NextResponse.json({ success: true, task });
  },

  recordCompleteness: async (raw, ctx) => {
    const data = validate.recordCompleteness(raw);
    const task = await createTask(ctx, {
      subject: `Completeness check PASSED — ${data.familyName}`,
      householdId: data.householdId,
      description: `All required information verified by Min at ${new Date().toISOString()}:\n` +
        data.checks.map(c => `✓ ${c}`).join("\n"),
    });
    return NextResponse.json({ success: true, task });
  },

  recordPaperwork: async (raw, ctx) => {
    const data = validate.recordPaperwork(raw);
    const inputs: TaskInput[] = data.envelopes.map(envelope => ({
      subject: `Paperwork generated — ${envelope.name}`,
      householdId: data.householdId,
      description: `Envelope: ${envelope.name}\nDocuments: ${envelope.documents.join(", ")}\nGenerated by Min at ${new Date().toISOString()}`,
    }));
    const { records: tasks } = await createTasksBatch(ctx, inputs);
    return NextResponse.json({ success: true, tasks, count: tasks.length });
  },

  recordDocusignConfig: async (raw, ctx) => {
    const data = validate.recordDocusignConfig(raw);
    const task = await createTask(ctx, {
      subject: `DocuSign configured — ${data.envelopeCount} envelopes for ${data.familyName}`,
      householdId: data.householdId,
      description: data.config.map(c => `${c.envelope}: ${c.recipients}`).join("\n") +
        `\n\nTemplates matched at 100%. Configured by Min at ${new Date().toISOString()}`,
    });
    return NextResponse.json({ success: true, task });
  },

  sendDocusign: async (raw, ctx) => {
    const data = validate.sendDocusign(raw);
    const today = new Date().toISOString().split("T")[0];
    const inputs: TaskInput[] = data.envelopes.map(envelope => ({
      subject: `SEND DOCU — ${envelope.name}`,
      householdId: data.householdId,
      contactId: data.primaryContactId,
      status: "Not Started" as const,
      priority: "High" as const,
      activityDate: today,
      description: `DocuSign envelope sent to: ${envelope.signers.join(", ")}\nCC: AdviceOne Ops, ${custodian.docusignCC || custodian.shortName + " DocuSign"}\nSubject: "${envelope.emailSubject}"\n\nSent by Min at ${new Date().toISOString()}`,
    }));
    const { records: tasks } = await createTasksBatch(ctx, inputs);

    await fireWorkflowTrigger(ctx, "docusign_sent", data.householdId, data.envelopes[0]?.name || "Client");
    return NextResponse.json({ success: true, tasks, count: tasks.length });
  },
};
